name = oneCol
description =  1 column layout .
;preview = preview.png
template = oneCol-layout

; Regions
regions[header]         = Header
regions[navigation]     = Navigation bar
;regions[highlighted]    = Highlighted
;regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
;regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/oneCol/oneCol.layout.css
